/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useSession, signIn, signOut } from "next-auth/react"
import MainLayout from "../../layouts/MainLayout";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Horus System - Inicio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="min-h-screen flex flex-col items-center justify-center gap-10 bg-gradient-to-br from-[#5afeb7] to-[#448cf2]">
            <Link href="/teacher" className="m-5 bg-white w-48 h-10 flex items-center justify-center rounded-xl hover:bg-stone-200 duration-200 ">Ver Profesores</Link>
            <Link href="/student" className="m-5 bg-white w-48 h-10 flex items-center justify-center rounded-xl hover:bg-stone-200 duration-200 ">Ver Estuiantes</Link>
            <Link href="/admin" className="m-5 bg-white w-48 h-10 flex items-center justify-center rounded-xl hover:bg-stone-200 duration-200 ">Ver Administracion</Link>
        </main>
      {/* <MainLayout>
      </MainLayout> */}
    </>
  );
};

export default Home;
